<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns0="http://www.example.org"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:client="http://xmlns.oracle.com/HelloWorldSOA/ORDSInsertPOST/InsertEmployee"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/InsertEmployee.wsdl"/>
        <oracle-xsl-mapper:rootElement name="employeeList" namespace="http://www.example.org"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/InsertEmployee.wsdl"/>
        <oracle-xsl-mapper:rootElement name="employeeList" namespace="http://www.example.org"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI FEB 19 18:07:12 IST 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <ns0:employeeList>
      <ns0:employee>
        <ns0:empid>
          <xsl:value-of select="/ns0:employeeList/ns0:employee/ns0:empid"/>
        </ns0:empid>
        <ns0:empname>
          <xsl:value-of select="/ns0:employeeList/ns0:employee/ns0:empname"/>
        </ns0:empname>
        <ns0:job>
          <xsl:value-of select="/ns0:employeeList/ns0:employee/ns0:job"/>
        </ns0:job>
        <ns0:managerid>
          <xsl:value-of select="/ns0:employeeList/ns0:employee/ns0:managerid"/>
        </ns0:managerid>
        <ns0:salary>
          <xsl:value-of select="/ns0:employeeList/ns0:employee/ns0:salary"/>
        </ns0:salary>
        <ns0:comm>
          <xsl:value-of select="/ns0:employeeList/ns0:employee/ns0:comm"/>
        </ns0:comm>
        <ns0:deptno>
          <xsl:value-of select="/ns0:employeeList/ns0:employee/ns0:deptno"/>
        </ns0:deptno>
      </ns0:employee>
    </ns0:employeeList>
  </xsl:template>
</xsl:stylesheet>
